config/routes.rb
Arturo::Application.routes.draw do
  root to: 'homepage#index'

  get '/auth/github/callback', to: 'omniauth_github#callback'

  get '/documentation',  to: 'documentation#index'
  get '/builds',         to: 'builds#index'
  get '/builds/:id',     to: 'builds#show', as: :build
  get '/badge/:repo_id', to: 'badge#show', as: :badge

  post '/hooks/github',  to: 'hooks#github'

  scope '/user', as: :user do
    get '/logout',          to: 'users#logout'
    get '/login/callback',  to: 'omniauth_github#callback'
    get '/settings',        to: 'users#settings'
    post '/charge/:plan',   to: 'users#charge', as: :charge
  end

  scope '/repositories',  as: :repositories do
    get    '/',           to: 'repositories#index'
    get    '/org/:org',   to: 'repositories#index',      as: :org
    get    '/sync',       to: 'repositories#sync',       as: :sync
    get    '/:id',        to: 'repositories#show',       as: :show
    put    '/:id/follow', to: 'repositories#follow',     as: :follow
    delete '/:id/follow', to: 'repositories#unfollow',   as: :unfollow 
    get    '/:id/build',  to: 'repositories#build',      as: :build
    get    '/:id/last_build.:format', to: 'repositories#last_build', as: :last_build
  end


  constraints lambda { |request| AdminConstraint.admin?(request) } do
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  protect_from_forgery with: :exception
  before_filter :check_login, except: [:show, :last_build]

  authorize_actions_for RepoAuthorizer
  authority_actions follow:     'create',
                    unfollow:   'update',
                    build:      'update',
                    sync:       'read',
                    last_build: 'read'

  def sync
    if(current_user[:loading_repos])
      redirect_to repositories_path, alert: 'Sync already in progress'
    else
      current_user.update(loading_repos: true)
      RepoSyncWorker.perform_async(session[:user_id])
      redirect_to repositories_path
    end
  end

  def index
    @user           = current_user
    @last_updated   = current_user[:last_sync_at]
    @following      = Follower.where(user: current_user).map(&:repo_id)
    @org            = (params[:org] || current_user[:login]).downcase
    @repositories   = user_repositories(current_user[:id], @org)
    @orgs           = Repo.user_orgs(current_user[:id])
    @partial        = @repositories.empty? ? 'no_repos' : 'repo_list'
    @sync_icon      = current_user[:loading_repos] ?  'spinner spin' : 'github-alt'
    @pusher_channel = "#{current_user.digest}-repositories"
  end

  def show
    @repo           = Repo.includes(:builds).find(params[:id])
    authorize_action_for @repo

    @builds         = @repo.builds.page(params[:page]).per(5)
    @badge_markdown = badge_markdown(@repo.id)
    @last_build     = Build.last_successful_build(@repo.id)
    @last_assets    = @last_build && @last_build.assets
    @pusher_channel = "#{current_user.digest}-builds-#{@repo.id}"
  end

  def follow
    repo = find_and_authorize(params[:id])

    Follower.create(user: current_user, repo: repo)
    GithubCreateHookWorker.perform_async(repo[:id])
    redirect_to repositories_show_path(repo), notice: "You are now following #{repo.name}"
  end

  def unfollow
    repo = find_and_authorize(params[:id])

    Follower.find_by(user: current_user, repo: repo).destroy
    GithubRemoveHookWorker.perform_async(repo[:id])
    redirect_to repositories_path, notice: "You are no longer following #{repo.name}"
  end

  def last_build
    repo   = find_and_authorize(params[:id])
    format = params[:format].downcase

    @asset = Build
      .last_successful_build(repo.id)
      .assets
      .find_by("url LIKE ?", "%.#{format}")

    @asset.nil? ? 
      render(nothing: true, status: 404) : redirect_to(@asset.url)
  end

  def build
    repo = find_and_authorize(params[:id])

    QueueBuildWorker.perform_async(repo[:id])
    redirect_to repositories_show_path(repo[:id]), notice: "A build has been queued for #{repo.name}"
  end

  private
  def authority_forbidden(error)
    return super unless action_name == "follow"
    Authority.logger.warn(error.message)
    redirect_to repositories_path, 
        alert: 'You have reached your private repo limit, please upgrade your account on the settings page.'
  end

  def find_and_authorize(repo_id)
    find_repo(repo_id).tap do |repo|
      authorize_action_for repo
    end
  end

  def find_repo(repo_id)
    Repo.find(repo_id)
  end

  def user_repositories(user_id, org)
     Repo.user_repositories(user_id, org).page(params[:page]).per(25)
  end

  def badge_markdown(repo_id)
    badge_url = badge_url(repo_id: repo_id, only_path: false)
    repo_url  = repositories_show_url(id: repo_id)
    "[![Build Status](#{badge_url})](#{repo_url})"
  end
end

app/controllers/repository_controller.rb
class RepositoryController < ApplicationController
  protect_from_forgery with: :exception
  before_filter :check_login, except: [:show]

  authorize_actions_for RepoAuthorizer
  authority_actions follow:   'update', 
                    unfollow: 'update', 
                    build:    'update',
                    sync:     'read'

  def sync
    if(current_user[:loading_repos])
      redirect_to repositories_path, alert: 'Sync already in progress'
    else
      current_user.update(loading_repos: true)
      RepoSyncWorker.perform_async(session[:user_id])
      redirect_to repositories_path
    end
  end

  def index
    @last_updated   = current_user[:last_sync_at]
    @following      = Follower.where(user: current_user).map(&:repo_id)
    @org            = params[:org] || current_user[:login]
    @repositories   = user_repositories(current_user[:id], @org)
    @orgs           = Repo.user_orgs(current_user[:id])
    @partial        = @repositories.empty? ? 'no_repos' : 'repo_list'
    @sync_icon      = current_user[:loading_repos] ?  'spinner spin' : 'github-alt'
    @pusher_channel = "#{current_user.digest}-repositories"
  end

  def show
    @repo           = Repo.includes(:builds).find(params[:id])
    @builds         = @repo.builds.page(params[:page]).per(5)
    @badge_markdown = badge_markdown(@repo[:id])
    @last_build     = Build.where(repo: @repo, status: :success).first
    @last_assets    = @last_build && @last_build.assets
    @pusher_channel = "#{current_user.digest}-builds-#{@repo[:id]}"

    authorize_action_for @repo
  end

  def follow
    repo = Repo.find(params[:id])
    authorize_action_for repo

    Follower.create(user: current_user, repo: repo)
    GithubCreateHookWorker.perform_async(repo[:id])
    redirect_to repositories_path, notice: "You are now following #{repo.name}"
  end

  def unfollow
    repo = Repo.find(params[:id])
    authorize_action_for repo

    Follower.where(user: current_user, repo: repo).first.destroy
    GithubRemoveHookWorker.perform_async(repo[:id])
    redirect_to repositories_path, notice: "You are no longer following #{repo.name}"
  end

  def build
    repo = Repo.find(params[:id])
    authorize_action_for repo

    QueueBuild.queue_build(repo[:id])
    redirect_to repositories_show_path(repo[:id]), notice: "A build has been queued for #{repo.name}"
  end

  private
  def user_repositories(user_id, org)
     Repo.user_repositories(user_id, org).page(params[:page]).per(25)
  end

  def badge_markdown(repo_id)
    badge_url = badge_url(repo_id: repo_id, only_path: false)
    repo_url  = repositories_show_url(id: repo_id)
    "[![Build Status](#{badge_url})](#{repo_url})"
  end
end

app/helpers/repository_helper.rb
module RepositoryHelper
  def asset_button_link(asset)
    url       = asset.url
    extension = File.extname(url) 
    content_tag(:a, class: 'button secondary radius', href: url) do
      ext_icon(extension) + human_readable_ext(extension)
    end
  end

  def tab_link(user, org) 
    disabled_class = org == @org ? 'disabled' : 'secondary'
    link_to tab_label(user, org), 
            repositories_org_path(org),
            class: "button tiny org #{disabled_class}"
  end

  def repo_badge(repo_id, markdown)
    image = badge_url(repo_id: repo_id)
    render('repo_badge', image: image,
                         markdown: @badge_markdown)
  end

  def button(text, location, other_classes = [])
    classes = %w(action button tiny radius) << other_classes 
    link_to text.html_safe, location, class: classes.join(" ")
  end

  def followed_org_count(user, org)
    Follower
      .with_user(user)
      .where(repos: { org: org })
      .count
  end

  private
  def ext_icon(extension)
    fa_icon(icons[extension])
  end

  def human_readable_ext(extension)
    return extensions[extension] if extensions.include?(extension)
  end

  def icons
   { ".pdf" => 'file-pdf-o',
     ".html" => 'file-code-o',
     ".epub" => 'file-o',
     ".mobi" => 'file-o'}
  end

  def extensions
    { ".pdf" => 'PDF',
      ".html" => 'Read Online',
      ".epub" => 'EPUB',
      ".mobi" => 'MOBI'}
  end

  def tab_label(user, org)
    count = followed_org_count(user, org)
    tag   = content_tag(:span, count, class: "label secondary radius")
    tag   = count == 0 ? '' : tag

    "#{org} #{tag}".html_safe
  end

end

app/views/repositories/_action_buttons.html.erb
<div class="actions columns small-4 right">
  <%= button "#{fa_icon('github')} Github", @repo.html_url, "secondary" %>
  <%= button "Badges", '#', "secondary badges" %>
  <%= button "Build", repositories_build_path(@repo.id) %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".actions a.badges").click(function() {
      $(".row.badges").toggle();
      return false;
    });
  });
</script>

app/views/repositories/_asset_buttons.html.erb
<div class="row">
  <div class="assets small-7 columns small-centered">
    <% assets.each do |asset| %>
      <%= asset_button_link(asset) %>
    <% end %>
  </div>
</div>

app/views/repositories/_last_build.html.erb
<div class="columns small-8 left">
  <div class="information">
    <em>
      The last successful build for this repo was 
      <%= link_to "#{@last_build.repo.name} [#{limit_string(@last_build.commit, 4)}]", build_path(@last_build) %>.
    </em>
  </div>
</div>

app/views/repositories/_no_repos.html.erb
Could not find any repos for this user.  Please create one on Github and <a href="/repositories/sync">sync</a>.

app/views/repositories/_org_list.html.erb
  <% @orgs.each do |org| %>
    <%= tab_link(@user, org) %>
  <% end %>

app/views/repositories/_repo_badge.html.erb
<div class="row badges">
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Badge</th>
          <th>Markdown</th>
        </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= image_tag(image) %></td>
        <td><%= text_field_tag('md', markdown) %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/repositories/_repo_list.html.erb
    <div class="row">
      <div class="small-12 columns">
        <table>
          <thead>
            <tr>
              <th>Repository</th>
              <th>Description</th>
              <th>Hooks</th>
              <th>Private</th>
              <th>Build</th>
            </tr>
          </thead>
          <tbody>
          <% @repositories.each do |repository| %> 
            <%= render 'repo_list_single', repository: repository %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="small-6 small-centered columns">
        <%= paginate @repositories %>
      </div>
    </div>

app/views/repositories/_repo_list_single.html.erb
              <tr class="repository">
                <td class="name">
                  <%= repository_link(@following, repository) %> 
                </td>
              <td class="description">
                <%= repository.description %>
              </td>
              <td class="hooks">
                <a href="https://www.github.com/<%= repository.full_name %>/settings/hooks" target="_blank">
                  <%= fa_icon('wrench') %>
                </a>
              </td>
              <td class="visibility">
                <%= repository.private ? fa_icon('eye-slash', title: "Private") : fa_icon('eye', class: 'fade', title: "Public")%>
              </td>
 
              <td class="toggle">
                <%= following_link(@following, repository) %>
              </td>
            </tr>

app/views/repositories/index.html.erb
<div class="row repositories">
  <div class="small-12 columns">
    <div class="row">
      <div class="small-12 columns">
        <h1>Repositories</h1>
      </div>
    </div>

    <div class="row">
      <div class="small-9 columns">
        <div class="information">
          Repository list was last update from Github <em><%= timeago_tag @last_updated %></em>.
        </div>
      </div>
      <div class="small-3 columns">
        <%= link_to "#{fa_icon(@sync_icon)} Sync".html_safe, repositories_sync_path, class: "button secondary radius tiny sync right" %>
      </div>
    </div>

    <div class="small-12 columns org-list">
      <%= render 'org_list' unless @repositories.empty? %>
    </div>
    <%= render(@partial) %> 
  </div>
</div>

<script type="text/javascript"<>
  $(document).ready(function(){
    var pusher  = new Pusher("<%= Rails.configuration.pusher_key %>");
    var channel = pusher.subscribe('<%= @pusher_channel %>');
    channel.bind('sync_complete', function(data) {
      if(data.completed) location.reload();
    });
  });
</script>

app/views/repositories/show.html.erb
<div class="row repositories">
  <div class="row">
    <div class="columns small-6 left">
      <h2> <%= link_to @repo.name, @repo.html_url, target: "_blank"%> </h2>
    </div>
  </div>

  <div class="row">
    <%= render 'last_build', last_build: @last_build if @last_build %>
    <%= render 'action_buttons' %>
  </div>

  <%= repo_badge(@repo.id, @badge_markdown) %>

  <div class="row">
    <div class="columns small-12">
      <%= render('asset_buttons', assets: @last_assets) if @last_assets %>
    </div>
  </div>


  <div class="row builds">
    <div class="columns small-12">
      <h3>Builds History</h3>
      <%= render('builds/build_list') %>
    </div>
  </div>

</div>