config/routes.rb
Arturo::Application.routes.draw do
  root to: 'homepage#index'

  get '/auth/github/callback', to: 'omniauth_github#callback'

  get '/documentation',  to: 'documentation#index'
  get '/builds',         to: 'builds#index'
  get '/builds/:id',     to: 'builds#show', as: :build
  get '/badge/:repo_id', to: 'badge#show', as: :badge

  post '/hooks/github',  to: 'hooks#github'

  scope '/user', as: :user do
    get '/logout',          to: 'users#logout'
    get '/login/callback',  to: 'omniauth_github#callback'
    get '/settings',        to: 'users#settings'
    post '/charge/:plan',   to: 'users#charge', as: :charge
  end

  scope '/repositories',  as: :repositories do
    get    '/',           to: 'repositories#index'
    get    '/org/:org',   to: 'repositories#index',      as: :org
    get    '/sync',       to: 'repositories#sync',       as: :sync
    get    '/:id',        to: 'repositories#show',       as: :show
    put    '/:id/follow', to: 'repositories#follow',     as: :follow
    delete '/:id/follow', to: 'repositories#unfollow',   as: :unfollow 
    get    '/:id/build',  to: 'repositories#build',      as: :build
    get    '/:id/last_build.:format', to: 'repositories#last_build', as: :last_build
  end


  constraints lambda { |request| AdminConstraint.admin?(request) } do
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/models/build.rb
class Build < ActiveRecord::Base
  include Authority::Abilities

  default_scope { order(created_at: :desc) }

  belongs_to :repo
  has_one    :user, through: :repo
  has_many   :assets
  has_one    :build_diff
  
  def update_status(status, message = nil)
    build_status.update(status, message)
  end

  def assign_attributes(attributes)
    attributes.each { |key, value| send("#{key}=", value) }
  end

  def self.user_builds(user)
    Build
      .includes(:repo)
      .where(repos: { user_id: user.id}) 
  end

  def self.last_successful_build(repo_id, branch = :master)
    branch ||= :master
    where(repo_id: repo_id, branch: branch, status: :success).first
  end

  private
  def build_status
    BuildStatus.new(self) 
  end
end

app/controllers/build_controller.rb
class BuildController < ApplicationController
  protect_from_forgery with: :exception

  before_filter :check_login, except: [:show]
  authorize_actions_for BuildAuthorizer, except: :index

  def index
    @builds  = user_builds.page(params[:page]).per(25)
    @partial = resolve_partial(@builds)
    @pusher_channel = "#{current_user.digest}-builds"
  end

  def show
    @build  = Build.includes(:assets, :user).find(params[:id])
    authorize_action_for @build

    @diff   = @build.build_diff
    @repo   = @build.repo
    @assets = @build.assets
  end

  private
  def resolve_partial(builds)
    builds.empty? ? 'no_builds' : 'build_list' 
  end

  def user_builds(user_id = current_user[:id])
    Build.includes(:repo).where("repos.user_id" => user_id)
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  protect_from_forgery with: :exception

  before_filter :check_login, except: [:show]
  authorize_actions_for BuildAuthorizer, except: :index

  def index
    @builds  = user_builds.page(params[:page]).per(25)
    @partial = resolve_partial(@builds)
    @pusher_channel = "#{current_user.digest}-builds"
  end

  def show
    @build  = Build.includes(:assets, :user).find(params[:id])
    authorize_action_for @build

    @diff   = @build.build_diff
    @repo   = @build.repo
    @assets = @build.assets
  end

  private
  def resolve_partial(builds)
    builds.empty? ? 'no_builds' : 'build_list' 
  end

  def user_builds(user_id = current_user[:id])
    Build.includes(:repo).where("repos.user_id" => user_id)
  end
end

app/helpers/build_helper.rb
module BuildHelper
  def link_to_build(build)
    link_to "#{build.repo.name} [#{limit_string(build.commit, 4)}]", 
      url_for(controller: 'builds', action: 'show', 
              id: build[:id], only_path: true)
  end

  def link_to_commit(build)
    link_to limit_string(build.commit, 8), 
            build.commit_url, 
            target: '_blank'
  end

  def branch_name(branch)
    limit_string(branch, 10)
  end

  def message(message)
    limit_string(message, 49)
  end

  def status_has_spinner?(status)
    parsed_status = status.to_s.downcase
    ['building', 'queued', 'uploading'].any? do |spinner_status|
      parsed_status.include?(spinner_status)
    end
  end

  def icon(status)
    if status_has_spinner?(status)
      fa_icon("spinner spin") 
    elsif status == "failure" || status == "canceled"
      fa_icon("times-circle") 
    elsif status == "success"
      fa_icon("check-circle") 
    else
      ""
    end
  end

  def build_status(status)
    output = icon(status)
    output << " #{status}"
  end

  def limit_string(string, max)
    return "" unless string
    return string if string.length <= max
    string[0..max]  << "..."
  end

  def link_to_author(author, url, avatar)
    image = (avatar && image_tag(avatar, width: "24", class: "author-avatar")) || ""
    link_to("#{image} #{author}".html_safe, url, target: "_blank")
  end

  def pusher_key
    Rails.configuration.pusher_key
  end
end

app/views/builds/_assets.html.erb
        <div class="row">
          <div class="small-12 columns">
            <table class="assets">
              <thead>
                <tr>
                  <th>File Name</th>
                  <th>Created</th>
                </tr>
              </thead>
              <tbody>
              <% assets.each do |asset| %> 
                  <tr class="asset">
                    <td class="url">
                      <%= link_to File.basename(asset.url), asset.url %>
                    </td>
                    <td class="created">
                      <%= timeago_tag asset.created_at %>
                    </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>

app/views/builds/_build_diff.html.erb
<div class="row">
  <div class="small-12 columns">
    <br/>
    <br/>
    <b>Diff: </b>
    <br/>
    <%= link_to File.basename(@diff[:url]), @diff[:url], target: "_blank" %>
  </div>
</div>

app/views/builds/_build_list.html.erb
    <div class="row builds">
      <div class="small-12 columns">
        <table>
          <thead>
            <tr>
              <th>Build</th>
              <th>Branch</th>
              <th>
                <%= fa_icon('github') %>
                Commit
              </th>
              <th>Message</th>
              <th>
                <%= fa_icon('github') %>
                Author
              </th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody class="body">
          <% @builds.each do |build| %> 
            <%= render 'builds/build_list_single', build: build %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="small-6 small-centered columns">
        <%= paginate @builds %>
      </div>
    </div>


    <script type="text/javascript"<>
      $(document).ready(function(){
        var pusher  = new Pusher('<%= pusher_key %>');
        var channel = pusher.subscribe('<%= @pusher_channel %>');

        channel.bind('new', function(template) {
          var $el = $(".builds .body").prepend(template);
        });

        channel.bind('status_update', function(data) {
          var $el       = $(".build#" + data.id + " .status"),
              cssClass  = data.css_class,
              newStatus = data.status;
          $el.removeClass()
           .addClass("status")
           .addClass(cssClass)
           .html(newStatus);
        });
      });
    </script>

app/views/builds/_build_list_single.html.erb
        <tr class="build" id="<%= build.id %>">
          <td class="name"><%= link_to_build(build) %></td>
          <td class="branch"><%= branch_name(build.branch) %></td>
          <td class="commit"><%= link_to_commit(build) if build.commit%></td>
          <td class="message"><%= message(build.message) %></td>
          <td class="author">
            <%= link_to_author(build.author, build.author_url, build.author_avatar) %>
          </td>
          <td class="status <%= build.status.downcase %>">
            <%= build_status(build.status) %>
          </td>
        </tr>

app/views/builds/_failure_message.html.erb
<div class="row">
  <div class="small-12 columns">
    <br/>
    <b>Error: </b>
    <br/>
    <%= @build.error %>
  </div>
</div>

app/views/builds/_no_builds.html.erb
<p>
You do not have any builds.
</p>

<p>
Visit one of your <%= link_to "repositories", repositories_path %> to
kick off a build manually (or push to a followed repository).
</p>

app/views/builds/index.html.erb
<div class="row repositories">
  <div class="small-12 columns">
    <div class="row">
      <div class="small-12 columns">
        <h1>Builds</h1>
      </div>
    </div>
    <%= render(@partial) %> 
  </div>
</div>

app/views/builds/show.html.erb
    <div class="row build">
      <div class="small-12 columns">
        <h2>
          <%= link_to @repo.full_name, repositories_show_path(@repo) %>
        </h2>
        <div class="row">
          <div class="small-6 columns">
            <div class="small-3 columns title">
              Author:
            </div>
            <div class="small-9 columns">
              <%= link_to_author(@build.author, @build.author_url, @build.author_avatar) %>
            </div>
          </div>

          <div class="small-6 columns">
            <div class="small-3 columns title">
              Branch: 
            </div>
            <div class="small-9 columns">
              <%= @build.branch %>
            </div>
          </div>


        </div>
        
        <div class="row">

          <div class="small-6 columns">
            <div class="small-3 columns title">
              Status:
            </div>
            <div class="small-9 columns">
              <%= @build.status.capitalize %>
            </div>
          </div>

          <div class="small-6 columns">
            <div class="small-3 columns title">
              Commit:
            </div>
            <div class="small-9 columns">
              <%= fa_icon('github') %>
              <%= link_to limit_string(@build.commit, 16) , @build.commit_url, target: '_blank' %>
            </div>
          </div>
 
        </div>

        <div class="row">

          <div class="small-6 columns">
            <div class="small-3 columns title">
              Started:
            </div>
            <div class="small-9 columns">
              <%= @build.started_at %>
            </div>
          </div>

          <div class="small-6 columns">
            <div class="small-3 columns title">
              Ended:
            </div>
            <div class="small-9 columns">
              <%= @build.ended_at %>
            </div>
          </div>
 
        </div>


        <div class="row">
          <div class="small-12 columns">
            <br/>
            <br/>
            <b>Commit Log: </b>
            <br/>
            <%= @build.message %>
          </div>
        </div>

        <%= render('build_diff', diff: @diff) if @diff %>
        <%= render('failure_message', message: @build.error) if @build.error %>

        <hr>

        <div class="row">
          <div class="small-12 columns">
            <h3> Assets </h3>
          <div>
        </div>
        <%= render('builds/assets', assets: @assets) %> 
      </div>
    </div>