config/routes.rb
Arturo::Application.routes.draw do
  root to: 'homepage#index'

  get '/auth/github/callback', to: 'omniauth_github#callback'

  get '/documentation',  to: 'documentation#index'
  get '/builds',         to: 'builds#index'
  get '/builds/:id',     to: 'builds#show', as: :build
  get '/badge/:repo_id', to: 'badge#show', as: :badge

  post '/hooks/github',  to: 'hooks#github'

  scope '/user', as: :user do
    get '/logout',          to: 'users#logout'
    get '/login/callback',  to: 'omniauth_github#callback'
    get '/settings',        to: 'users#settings'
    post '/charge/:plan',   to: 'users#charge', as: :charge
  end

  scope '/repositories',  as: :repositories do
    get    '/',           to: 'repositories#index'
    get    '/org/:org',   to: 'repositories#index',      as: :org
    get    '/sync',       to: 'repositories#sync',       as: :sync
    get    '/:id',        to: 'repositories#show',       as: :show
    put    '/:id/follow', to: 'repositories#follow',     as: :follow
    delete '/:id/follow', to: 'repositories#unfollow',   as: :unfollow 
    get    '/:id/build',  to: 'repositories#build',      as: :build
    get    '/:id/last_build.:format', to: 'repositories#last_build', as: :last_build
  end


  constraints lambda { |request| AdminConstraint.admin?(request) } do
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Authority::UserAbilities

  has_many :repos, dependent: :destroy
  has_many :followers, dependent: :destroy

  belongs_to :plan

  validates_presence_of   :uid, :provider, :name, :auth_token
  validates_uniqueness_of :uid

  def admin?
    email && email == 'ortuna@gmail.com'
  end
  
  def digest
    Digest::MD5.hexdigest("#{login}#{uid}")
  end

  def update_from_omniauth(auth = {})
    token = auth['credentials'] && auth['credentials']['token']
    return unless token
    self[:auth_token] = token
    save
  end

  alias_method :user_plan, :plan
  def plan
    user_plan || Plan.find_by(name: :open_source)
  end

  def within_repo_limit? 
    private_follow_count <= plan.repos
  end

  def repo_limit_reached?
    private_follow_count >= plan.repos
  end

  def self.create_with_omniauth(auth = {})
    return nil unless auth
    user       = User.new

    user.attributes = {
      provider:  auth['provider'],
      uid:       auth['uid'],
      login:     (auth['info'] && auth['info']['nickname'])  || nil,
      name:      (auth['info'] && auth['info']['name'])  || nil,
      email:     (auth['info'] && auth['info']['email'])  || nil,
      image_url: (auth['info'] && auth['info']['image']) || nil,
      auth_token:(auth['credentials'] && auth['credentials']['token']) || nil,
      role:      'author'
    }
    if user.save
      send_email(user[:id]) 
      user
    end
  end

  def self.find_with_omniauth(auth = {})
    return nil unless auth && auth[:uid]
    User.where(uid: auth[:uid]).first
  end

  private
  def private_follow_count 
    Follower
      .includes(:repo)
      .where(repos: {user_id: id, private: true})
      .count
  end

  def self.send_email(user_id)
    UserSignupEmailWorker.perform_async(user_id) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_filter :check_login, only: [:settings]
  before_filter :validate_plan, only: [:charge]

  def logout
    reset_session
    redirect_to root_path
  end

  def settings
    @user          = current_user
    @build_count   = build_count
    @follow_count  = follow_count
    @private_follow_count = private_follow_count
    @email         = current_user[:email]
  end

  def charge
    options = { token: params[:stripeToken], 
                email: params[:stripeEmail],
                user:  current_user,
                plan:  params[:plan] }

    Stripe::Subscribe.new(options).execute
  rescue
    flash[:alert] = "Could not complete transaction"
  ensure
    redirect_to user_settings_path
  end

  private
  def validate_plan
    unless valid_plan?(params[:plan])
      render status: :forbidden, nothing: true 
    end
  end

  def valid_plan?(plan_name) 
    Plan.find_by(name: plan_name) || false
  end

  def private_follow_count(user = current_user)
    follows(user, true).count
  end

  def follow_count(user = current_user)
    follows(user).count
  end

  def follows(user = current_user, private_only = false)
    options = { user_id: user.id }
    options[:private] = true if private_only

    Follower
      .includes(:repo)
      .where(repos: options) 
  end


  def build_count(user = current_user)
    Build.user_builds(user).count
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def plan_button(user_plan, plan, email)
    text    = plan_button_text(user_plan, plan.name)
    render partial(user_plan, plan, email), text: text, plan: plan, email: email
  end

  def partial(user_plan, plan, email)
    user = User.find_by(email: email)

    return 'disabled_button'       if current_plan?(user_plan, plan.name)
    return 'existing_subscription' if user.stripe_subscription_token
    'stripe_button'
  end

  def plan_button_text(user_plan, plan)
    return "Current" if current_plan?(user_plan, plan)
    return "Subscribe"
  end

  def current_plan?(user_plan, plan)
    user_plan.name == plan
  end

  def builds(is_priority)
    return "Priority Builds" if is_priority
    "Public Builds"
  end

  def price(string)
    return "Free" if string == 0
    return "$#{string.to_f/100}"
  end
end

app/views/users/_disabled_button.html.erb
<button type="submit" class="stripe-button-el disabled" style="visibility: visible;">
  <span style="display: block; min-height: 30px;">Current</span>
</button>

app/views/users/_existing_subscription.html.erb
<form action="<%= user_charge_path(plan.name) %>" method="POST">
  <button type="submit" class="stripe-button-el" style="visibility: visible;">
    <span style="display: block; min-height: 30px;">Switch</span>
  </button>
</form>

app/views/users/_stripe_button.html.erb
<form action="<%= user_charge_path(plan.name) %>" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe_pub_key %>"
    data-email="<%= email %>"
    data-name="Arturo.io"
    data-description="<%= plan.stripe_description %>"
    data-label="<%= text %>"
    data-panel-label="Subscribe"
    data-amount="<%= plan.price %>"
    data-allow-remember-me="false">
  </script>
</form>

app/views/users/settings.html.erb
<section class="settings">
  <div class="heading">
    <div class="row">

      <div class="small-4 columns stats">
        <h3><%= pluralize(@build_count, 'Build') %></h3>
        <h5><%= @email %></h5>
      </div>

      <div class="small-4 columns">
        <%= image_tag @user.image_url, class: 'avatar' %>
        <h1><%= @user.name %></h1>
        <p class="plan-info">
        Your current plan is "<%= @user.plan.human_name %>"
        </p>
      </div>

      <div class="small-4 columns stats">
        <h3><%= pluralize(@follow_count, 'Followed Repo') %></h3>
        <h5><%= pluralize(@private_follow_count, 'Private Repo') %></h5>
      </div>

 
    </div>
  </div>
  <section class="pricing">
    <div class="row">
      <% Plan.all.each do |plan| %>
        <div class="small-4 columns">
          <ul class="pricing-table">
            <li class="title"><%= plan.human_name %></li>
            <li class="price"><%= price(plan.price) %></li>
            <li class="description"><%= plan.description %></li>
            <li class="bullet-item">∞ public repos</li>
            <li class="bullet-item"><%= plan.repos %> private repo</li>
            <li class="bullet-item"><%= builds(plan.priority) %></li>
            <li class="cta-button">
            <%= plan_button(@user.plan, plan, @user.email) %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </section>
</section>